### ISSUE TITLE
There is no way to stop vsk project 

### ISSUE THREAD

**Issue by abubakar01914877870** [abey79/sketches#2]
Step to reproduce: 
1. Run a vsk project rising "vsk run project_name"
2. Now try to stop the project
3. Observe if I close the vpype viewer still in terminal it is running there is no way to stop that except I have to close the terminal

**Comment by abey79** [comment]
Did you update vsketch recently? Such a bug has been fixed recently: https://github.com/abey79/vsketch/issues/238
